export const REQUEST_EDGENODE_DATA = "REQUEST_EDGENODE_DATA"
export const SUCCESS_EDGENODE_DATA = "SUCCESS_EDGENODE_DATA"
export const FAILED_EDGENODE_DATA = "FAILED_EDGENODE_DATA"

export const FAILD_CONNECTION_TELEGRAM_SERVER = "FAILD_CONNECTION_TELEGRAM_SERVER"
export const SUCCESS_CONNECTION_TELEGRAM_SERVER = "SUCCESS_CONNECTION_TELEGRAM_SERVER"
export const REQUEST_CONNECTION_TELEGRAM_SERVER = "REQUEST_CONNECTION_TELEGRAM_SERVER"



